source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

target 'IpsLocation_Demo' do
    #pod 'IpsLocation', '~>1.0.0'
    #本地路径
    pod 'IpsLocation', :path => '../'
    #git路径
    #pod 'IpsLocation', :git => 'https://github.com/ipsmap/IpsLocation-iOS.git'
end
